# The URL the site will be built for
base_url = "https://mind-help.github.io/blog/"
theme = "zhuia"
title = "Mind-Help"
# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

default_language = "pt-br"

# Whether to build a search index to be used later on by a JavaScript library
# build_search_index = true

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = false

[extra]
# Put all your custom variables here
author = "Equipe Mind-Help"
show_author = true
show_categories = true
show_tags = true
read_more_prompt = "ler mais"
read_post_prompt = "ler post"
grid_size = "grid-lg"
katex = true
hamburger_menu = true
main_menu = [
	{url="/tags/", name="tags"},
	{url="/sobre/", name="sobre"},
	{url="/inscreva-se/", name="inscreva-se"},
]
social_links = [
	# {url = "https://t.me/zwitterio", name = "telegram"},
	# {url = "https://twitter.com/gicrisf", name = "twitter"},
    {url = "https://github.com/mind-help", name = "github"},
    {url = "https://instagram.com/mindhelp027", name = "instagram"},
    # {url = "", name = "facebook"},
]
footer_tagline = "Equipe Mind-Help"

[extra.sidebar]
# Enable/Disable sidebar
active=true

text_snippet="<strong>Bem Vindo!<strong/>"

author_bio = "Profissionais da saúde em parceria com a mind-help"
author_avatar = "avatar.png"

tweets_by="elonmusk"

popular_tags=true
archive=true
