base_url = "https://mind-help.github.io/blog/"
theme = "zhuia"
title = "Mind-Help"
compile_sass = true

default_language = "pt-br"

[markdown]
highlight_code = false

[extra]
# Put all your custom variables here
author = "Equipe Mind-Help"
show_author = true
show_categories = true
show_tags = true
read_more_prompt = "ler mais"
read_post_prompt = "ler post"
grid_size = "grid-lg"
katex = true
hamburger_menu = true
main_menu = [
	{url="/tags/", name="tags"},
	{url="/sobre/", name="sobre"},
	{url="/inscreva-se/", name="inscreva-se"},
]
social_links = [
    {url = "https://github.com/mind-help", name = "github"},
    {url = "https://instagram.com/mindhelp027", name = "instagram"},
]
footer_tagline = "Equipe Mind-Help"

[extra.sidebar]
active=true

text_snippet="<a href=\"bem-vindo\"><strong>Bem Vindo!<strong/></a>"

author_bio = "Nossa empresa é composta por 4 integrantes, onde visamos o propósito de ajudar o próximo via nosso APP para crises emergenciais."
author_avatar = "avatar.svg"

tweets_by="elonmusk"

popular_tags=true
archive=true
